name: Run Tests  # Name of the workflow

on:  # When to run
  push:
    branches: [main]  # On pushes to main
  pull_request:
    branches: [main]  # On PRs to main

jobs:  # The tasks
  test:
    runs-on: ubuntu-latest  # Use a GitHub virtual machine
    steps:
      - uses: actions/checkout@v3  # Download your code
      - name: Use Node.js  # Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Match your project's Node version (check package.json)
      - run: npm ci  # Install dependencies
      - run: npm test  # Run your Jest tests